
name: Backend CICD pipeline
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag value for docker image"
        required: true
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Tag
        id: set_tag
        run: |
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            echo "::set-output name=tag::${{ github.event.inputs.tag }}"
          else
            echo "::set-output name=tag::${{ github.ref }}"
          fi
          
      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: ${{ steps.set_tag.outputs.tag }}
        working-directory: backend
        run: |
          docker build -t mrigeshpatni/backend-crud:${{ steps.set_tag.outputs.tag }} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push mrigeshpatni/backend-crud:${{ steps.set_tag.outputs.tag }}
     
      - name: Debug docker image refrence
        run: echo "DOCKER_IMAGE=mrigeshpatni/backend-crud:${{ steps.set_tag.outputs.tag }}"
        
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop backend-container || true
            docker rm backend-container || true
            docker pull mrigeshpatni/backend-crud:${{ steps.set_tag.outputs.tag }}
            docker run -d -p 3333:3333 --name backend-container mrigeshpatni/backend-crud:${{ steps.set_tag.outputs.tag }}
