
name: Backend CICD pipeline
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: ${{ github.ref }}
        working-directory: backend
        run: |
          docker build -t mrigeshpatni/backend-crud:$IMAGE_TAG .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push mrigeshpatni/backend-crud:$IMAGE_TAG
     
      - name: Debug docker image refrence
        run: echo "DOCKER_IMAGE=mrigeshpatni/backend-crud:${{ github.ref }}"
        
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop backend-container || true
            docker rm backend-container || true
            docker pull mrigeshpatni/backend-crud:${{ github.ref }}
            docker run -d -p 3333:3333 --name backend-container mrigeshpatni/backend-crud:${{ github.ref }}
