
name: Backend CICD pipeline
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        run: |
          docker build -t backend-image:${{ github.ref }} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push backend-image:${{ github.ref }}
     
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop backend-container || true
            docker rm backend-container || true
            docker run -d -p 3333:3333 --name backend-container backend-image:${{ github.ref }}

