
name: Frontend CICD pipeline
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag value for docker image"
        required: true
  push:
    tags:
      - '*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Tag
        id: set_tag
        run: |
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.ref/refs\/tags\// }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: ${{ steps.set-tag.outputs.tag }}
        working-directory: frontend
        run: |
          docker build -t mrigeshpatni/frontend-crud:${{ steps.set-tag.outputs.tag }} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push mrigeshpatni/frontend-crud:${{ steps.set-tag.outputs.tag }}

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker run -d -p 80:80 --name frontend-container mrigeshpatni/frontend-crud:${{ steps.set-tag.outputs.tag }}


